### ISSUE TITLE
1.8.0 does not compile on VDS

### ISSUE THREAD

**Issue by RoyDodd** [Pure-Battlefield/TagPlugin#1]
This is the info from the plugin_log file:

System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: startIndex
   at System.String.Insert(Int32 startIndex, String value)
   at PRoCon.Core.Plugin.PluginManager.BuildPluginSource(FileInfo pluginFile) in f:\Programming\Revision Control\Git\Procon-1\src\PRoCon.Core\Plugin\PluginManager.cs:line 623
   at PRoCon.Core.Plugin.PluginManager.CompilePlugin(FileInfo pluginFile, String pluginClassName, CodeDomProvider pluginsCodeDomProvider, CompilerParameters parameters) in f:\Programming\Revision Control\Git\Procon-1\src\PRoCon.Core\Plugin\PluginManager.cs:line 636
   at PRoCon.Core.Plugin.PluginManager.CompilePlugins(PermissionSet pluginSandboxPermissions, List`1 ignoredPluginClassNames) in f:\Programming\Revision Control\Git\Procon-1\src\PRoCon.Core\Plugin\PluginManager.cs:line 841

**Comment by ra4king** [comment]
Uh... this is for another plugin. What you have told me in Teamspeak is that the Details and Plugin Settings tabs are blank?

**Comment by RoyDodd** [comment]
[19:19:05] Compiling pureLogServer.cs... Using Cache
[19:19:05] Loading pureLogServer... Loaded
[19:19:05] pureLog Server Edition Loaded!
[19:19:05] Compiling Tag... Exception
[19:19:05] System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: startIndex
   at System.String.Insert(Int32 startIndex, String value)
   at PRoCon.Core.Plugin.PluginManager.BuildPluginSource(FileInfo pluginFile) in f:\Programming\Revision Control\Git\Procon-1\src\PRoCon.Core\Plugin\PluginManager.cs:line 623
   at PRoCon.Core.Plugin.PluginManager.CompilePlugin(FileInfo pluginFile, String pluginClassName, CodeDomProvider pluginsCodeDomProvider, CompilerParameters parameters) in f:\Programming\Revision Control\Git\Procon-1\src\PRoCon.Core\Plugin\PluginManager.cs:line 636
   at PRoCon.Core.Plugin.PluginManager.CompilePlugins(PermissionSet pluginSandboxPermissions, List`1 ignoredPluginClassNames) in f:\Programming\Revision Control\Git\Procon-1\src\PRoCon.Core\Plugin\PluginManager.cs:line 841
[19:19:05] Compiling TeamspeakSync.cs... Using Cache
[19:19:06] Loading TeamspeakSync... Loaded
